import argparse
import csv
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from road_network import RoadDistanceCalculator, RoadNetworkLoader
from road_network.batch_router import BatchRouteCalculator


def generate_grid_network(csv_path: Path, grid_size: int, step: float):
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", encoding="utf-8", newline="") as fp:
        writer = csv.writer(fp)
        writer.writerow(["WKT"])
        for y in range(grid_size):
            lat = 13.0 + y * step
            for x in range(grid_size - 1):
                lon = 100.0 + x * step
                writer.writerow([f"LINESTRING({lon:.7f} {lat:.7f},{lon + step:.7f} {lat:.7f})"])
        for x in range(grid_size):
            lon = 100.0 + x * step
            for y in range(grid_size - 1):
                lat = 13.0 + y * step
                writer.writerow([f"LINESTRING({lon:.7f} {lat:.7f},{lon:.7f} {lat + step:.7f})"])


def generate_pairs(csv_path: Path, grid_size: int, step: float, pair_count: int):
    max_idx = grid_size - 1
    with csv_path.open("w", encoding="utf-8", newline="") as fp:
        writer = csv.DictWriter(
            fp,
            fieldnames=["Src NE Name", "Sink NE Name", "Src Lon", "Src Lat", "Sink Lon", "Sink Lat"],
        )
        writer.writeheader()
        for i in range(pair_count):
            sx = i % max_idx
            sy = (i * 7) % max_idx
            dx = min(max_idx, sx + 20 + (i % 30))
            dy = min(max_idx, sy + 20 + (i % 30))
            writer.writerow(
                {
                    "Src NE Name": f"SRC_{i:06d}",
                    "Sink NE Name": f"SINK_{i:06d}",
                    "Src Lon": f"{100.0 + sx * step:.7f}",
                    "Src Lat": f"{13.0 + sy * step:.7f}",
                    "Sink Lon": f"{100.0 + dx * step:.7f}",
                    "Sink Lat": f"{13.0 + dy * step:.7f}",
                }
            )


def write_report(report_path: Path, metrics: dict):
    report_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Batch Route Performance DT Report",
        "",
        "This report is generated by `DT_test/performance_dt.py` with synthetic WKT grid data.",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
    ]
    for key, value in metrics.items():
        lines.append(f"| {key} | {value} |")
    lines.extend(
        [
            "",
            "Notes:",
            "- The synthetic grid is deterministic and offline, so it is suitable for regression testing.",
            "- Increase `--grid-size` to stress million-level WKT edges.",
            "- The batch calculator uses thread workers that share the already-loaded CSR graph and spatial index in memory.",
        ]
    )
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--grid-size", type=int, default=220)
    parser.add_argument("--step", type=float, default=0.0005)
    parser.add_argument("--pairs", type=int, default=2000)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--threshold-km", type=float, default=30.0)
    parser.add_argument("--work-dir", type=Path, default=ROOT / "DT_test" / "generated")
    parser.add_argument("--report", type=Path, default=ROOT / "docs" / "batch_route_performance_dt_report.md")
    args = parser.parse_args()

    network_csv = args.work_dir / f"grid_{args.grid_size}.csv"
    pairs_csv = args.work_dir / f"pairs_{args.pairs}.csv"
    result_csv = args.work_dir / f"result_{args.grid_size}_{args.pairs}.csv"

    started = time.perf_counter()
    generate_grid_network(network_csv, args.grid_size, args.step)
    generate_pairs(pairs_csv, args.grid_size, args.step, args.pairs)
    generation_s = time.perf_counter() - started

    started = time.perf_counter()
    network = RoadNetworkLoader().load_csv(str(network_csv))
    load_s = time.perf_counter() - started

    calculator = RoadDistanceCalculator(network)
    started = time.perf_counter()
    summary = BatchRouteCalculator(network, calculator).run_csv(
        str(pairs_csv),
        str(result_csv),
        straight_distance_threshold_km=args.threshold_km,
        workers=args.workers,
    )
    batch_s = time.perf_counter() - started

    metrics = {
        "grid_size": args.grid_size,
        "WKT rows": 2 * args.grid_size * (args.grid_size - 1),
        "nodes": network.node_count,
        "undirected edges": network.undirected_edge_count,
        "pairs": args.pairs,
        "workers": args.workers,
        "threshold km": args.threshold_km,
        "generation seconds": f"{generation_s:.3f}",
        "load seconds": f"{load_s:.3f}",
        "batch seconds": f"{batch_s:.3f}",
        "avg ms per pair": f"{(batch_s * 1000.0 / max(1, args.pairs)):.3f}",
        "success": summary.success,
        "failed": summary.failed,
        "skipped by threshold": summary.skipped_by_threshold,
        "result csv MB": f"{result_csv.stat().st_size / 1024 / 1024:.2f}",
    }
    write_report(args.report, metrics)
    print(json.dumps(metrics, ensure_ascii=False, indent=2))
    print(f"Report: {args.report}")


if __name__ == "__main__":
    main()
